name: CI/CD Pipeline - Build, Push & PR (Same Repo)

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: fassir/hello-app 
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Update Kubernetes manifests
        run: |
          # O comando sed substituirá 'fassir/hello-app:.*' pela nova tag SHA.
          # O deployment.yaml deve estar na raiz do seu repositório hello-app.
          sed -i "s|image: ${{ env.DOCKER_IMAGE_NAME }}:.*|image: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" deployment.yaml
          
          echo "Conteúdo de deployment.yaml atualizado:"
          cat deployment.yaml 
        working-directory: ${{ github.workspace }}

      - name: Create Pull Request for manifest changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(app): Update hello-app image to ${{ env.IMAGE_TAG }}"
          branch: update-image-${{ github.sha }}
          delete-branch: true
          title: "Update hello-app image to ${{ env.IMAGE_TAG }}"
          body: |
            Atualiza a imagem do `hello-app` no manifesto do Kubernetes para a tag `${{ env.IMAGE_TAG }}`.
            Gerado automaticamente pelo workflow de CI/CD.
          base: main
