name: CI/CD Pipeline - Build, Push & Update ArgoCD Manifests (Two Repositories)

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: fassir/hello-app
  IMAGE_TAG: ${{ github.sha }}

  MANIFESTS_REPO_OWNER: fassir
  MANIFESTS_REPO_NAME: hello-manifests
  # O caminho DENTRO do repositório hello-manifests onde estão os .yaml
  MANIFESTS_PATH_IN_REPO: hello-app 
  
  # --- NOVO: Caminho local onde o repositório de manifestos será clonado ---
  LOCAL_MANIFESTS_CLONE_PATH: manifests-repo-clone 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Permissão para a ação 'peter-evans/create-pull-request' fazer push
      pull-requests: write # Permissão para a ação 'peter-evans/create-pull-request' criar o PR

    steps:
      - name: Checkout application code (hello-app)
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Checkout ArgoCD manifests repository (hello-manifests)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO_OWNER }}/${{ env.MANIFESTS_REPO_NAME }}
          # Clona o hello-manifests para o caminho definido em LOCAL_MANIFESTS_CLONE_PATH
          path: ${{ env.LOCAL_MANIFESTS_CLONE_PATH }} 
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }} # Usa SSH para autenticar (precisa da Deploy Key)

      - name: Update Kubernetes manifests
        run: |
          # Navega para a pasta CORRETA dentro do repositório de manifestos clonado
          cd ${{ env.LOCAL_MANIFESTS_CLONE_PATH }}/${{ env.MANIFESTS_PATH_IN_REPO }}
          
          # Atualiza a tag da imagem no deployment.yaml
          sed -i "s|image: ${{ env.DOCKER_IMAGE_NAME }}:.*|image: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" deployment.yaml
          
          echo "Conteúdo de deployment.yaml atualizado:"
          cat deployment.yaml # Isso imprimirá o conteúdo atualizado nos logs para depuração
        working-directory: ${{ github.workspace }} # Define o diretório de trabalho base como a raiz do workspace

      - name: Create Pull Request for manifest changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(app): Update hello-app image to ${{ env.IMAGE_TAG }}"
          branch: update-image-${{ github.sha }} # Nome da branch do Pull Request
          delete-branch: true
          title: "Update hello-app image to ${{ env.IMAGE_TAG }}"
          body: |
            Atualiza a imagem do `hello-app` no manifesto do Kubernetes para a tag `${{ env.IMAGE_TAG }}`.
            Gerado automaticamente pelo workflow de CI/CD.
          base: main # A branch base para o Pull Request (a branch 'main' do hello-manifests)
          repository: ${{ env.MANIFESTS_REPO_OWNER }}/${{ env.MANIFESTS_REPO_NAME }}
          # --- NOVO: Onde a ação deve procurar as mudanças para o PR ---
          path: ${{ env.LOCAL_MANIFESTS_CLONE_PATH }}
