# .github/workflows/main.yml
name: CI/CD Pipeline - Build, Push & Update ArgoCD Manifests

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/hello-app
  IMAGE_TAG: ${{ github.sha }}
  MANIFESTS_PATH: k8s
  MANIFESTS_REPO_OWNER: fassir
  MANIFESTS_REPO_NAME: hello-manifests

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Checkout ArgoCD manifests repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}
          path: ${{ env.MANIFESTS_REPO }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update Kubernetes manifests
        run: |
          cd ${{ env.MANIFESTS_REPO }}/${{ env.MANIFESTS_PATH }}
          sed -i "s|image: .*|image: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" deployment.yaml

      - name: Create Pull Request for manifest changes
        uses: /create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(app): Update hello-app image to ${{ env.IMAGE_TAG }}"
          branch: update-image-${{ github.sha }}
          delete-branch: true
          title: "Update hello-app image to ${{ env.IMAGE_TAG }}"
          body: |
            Atualiza a imagem do `hello-app` no manifesto do Kubernetes para a tag `${{ env.IMAGE_TAG }}`.
            Gerado automaticamente pelo workflow de CI/CD.
          base: main
          repository: ${{ env.MANIFESTS_REPO }}
